index:
  class: File
  path: /media/francesco/Volume/Work/genomes/miceIndexed/GRCm39.fna
index_chm13:
  class: File
  path: /backup/fpantini/genomes/chm13_indexed/chm13v2.0.fa
threads: 11
db_path:
  class: File
  path: /backup/krakenDB/Total/hash.k2d
meta_path:
  class: Directory
  path: /media/francesco/Volume/Work/metaphlan
fastq_directory:
  class: Directory
  location: /media/francesco/Seagate_Basic/Università/kneadData/Try/input
biom_input: 
  class: File
  path: /media/francesco/Volume/Work/bioms/AMCTRL15_output.biom
knead_directory:
  class: Directory
  path: /home/fpantini/metaphlan/kneaddata
human_contaminant:
  class: Directory
  path: /media/francesco/Seagate_Basic/Università/kneadData/hummanContaminant


  