index:
  class: File
  path: /storage/fpantini/reference/indexGenome/hg38.fa 
index_chm13:
  class: File
  path: /storage/fpantini/reference/indexGenome/chm13v2.0.fa 
threads: 7 
db_path:
  class: File
  path: /storage/fpantini/reference/krakenDB/Fungi/hash.k2d
fastq_directory:
  class: Directory
  location: /storage/fpantini/dataInput 


  