index:
  class: File
  path: /media/francesco/Volume/Work/genomes/miceIndexed/GRCm39.fna
index_chm13:
  class: File
  path: /backup/fpantini/genomes/chm13_indexed/chm13v2.0.fa
threads: 11
db_path:
  class: File
  path: /backup/krakenDB/Total/hash.k2d
meta_path:
  class: Directory
  path: /media/francesco/Volume/Work/metaphlan
fastq_directory:
  class: Directory
  location: /media/francesco/Volume/Work/unitor_001_0324/raw_sequences/UNITOR-001-CA_03
biom_input: 
  class: File
  path: /media/francesco/Volume/Work/bioms/AMCTRL15_output.biom
output_dir:

  