index:
  class: File
  path: /backup/Ref/hg38/hg38.fa
index_chm13:
  class: File
  path: /backup/fpantini/genomes/chm13_indexed/chm13v2.0.fa
threads: 30
db_path:
  class: File
  path: /backup/fpantini/braken_DB/hash.k2d
meta_path:
  class: Directory
  path: /backup/fpantini/metaphlan_DB_411
fastq_directory:
  class: Directory
  location: /backup/MultipleSclerosis/DataOriginals/Controls
biom_input: 
  class: File
  path: /media/francesco/Volume/Work/bioms/AMCTRL15_output.biom
est_abundance: 
  class: File
  path: /home/fpantini/microbiomeAnalysisCWL/kraken2Container/Bracken/src/est_abundance.py
report_folder:
  class: Directory
  path: /home/fpantini/reports
kmer_distrib:
  class: File
  path: /backup/fpantini/braken_DB/database150mers.kmer_distrib
classification_level: "S"
threshod: 30
alpha: _aboundance.braken
mice_index:
  class: File
  location: /backup/fpantini/genomes/GRCm39_indexed/GRCm39.fna
chocophlan_DB:
  class: Directory
  path: /backup/fpantini/humann_DB/chocophlan
uniref_DB:
  class: Directory
  path: /backup/fpantini/humann_DB/uniref  
mice_db:
  class: Directory 
  path: /backup/fpantini/kneaddata/miceDB
human_contaminant:
  class: Directory
  path: /backup/fpantini/kneaddata/humanContaminant

