index:
  class: File
  path: /home/scontaldo/variantCalling/hg38-20221027/indexGenome/hg38.fa
threads: 21 
db_path:
  class: File
  path: /fungi/krakenDB/Virus/hash.k2d
fastq_directory:
  class: Directory
  location: data 
raw_chm13:
  class: File
  path: /storage/fpantini/reference/indexGenome/chm13v2.0.fa
method: 2 #0 is the default algorithm
          #1 IS linear-time algorithm for constructing suffix array
          #2 Algorithm implemented in BWT-SW(works with whole human genome)