output_meta_dir:
  class: Directory
  path: /media/francesco/Volume/newMetaphlanResults/allMeta/output


three_tables:
  class: File
  path: /home/francesco/Desktop/git/mine/microbiomeAnalysisCWL/tools/mpa_vJan21_CHOCOPhlAnSGB_202103.nwk
