index:
  class: File
  path: /backup/Ref/hg38/hg38.fa
index_chm13:
  class: File
  path: /backup/fpantini/genomes/chm13_indexed/chm13v2.0.fa
threads: 30
db_path:
  class: File
  path: /backup/krakenDB/Total/hash.k2d
meta_path:
  class: Directory
  path: /backup/fpantini/metaphlan_db_4.1
fastq_directory:
  class: Directory
  location: /backup/fpantini/file_piccoli/comp
biom_input: 
  class: File
  path: 
output_dir: 
  class: Directory
  path: ./

  