est_abundance: 
  class: File
  path: /home/fpantini/microbiomeAnalysisCWL/kraken2Container/Bracken/src/est_abundance.py
report_folder:
  class: Directory
  path: /home/fpantini/reports
kmer_distrib:
  class: File
  path: /home/fpantini/database150mers.kmer_distrib
classification_level: "S"
threshod: 30
alpha: aboundance_results.braken