FROM qbioturin/kraken2:0.1
LABEL maintainer="pandafake589@gmail.com"

WORKDIR /

COPY getOTU.py .
COPY countTotalOTU.py .
COPY kraken2.sh .
COPY computeAlpha.py .
COPY  kreport2mpa.py . 
COPY  transformInMeta.py .
